### ISSUE TITLE
Error code 1 

### ISSUE THREAD

**Issue by vitstra** [themsiqueira/valorant#1]
After starting the game it displays error code 1 and the only option is to quit game. I tried reinstalling the game but it ended up the same.

Os: Kubuntu 20.04

**Comment by Busch** [comment]
Same here on RHEL 7.6

**Comment by utherbone** [comment]
The same in Xubuntu focal.
Somehow is not able to connect to the internet

**Comment by themsiqueira** [comment]
This problem is due to riot vanguard, it depends on a very specific windows driver and with that you cannot play, we probably will not be able to run the new riot games

**Comment by themsiqueira** [comment]
I will take the package off
