### ISSUE TITLE
Wine 6.0

### ISSUE THREAD

**Issue by VerXay** [themsiqueira/valorant#3]
Wine 6.0 got released and the change log is kinda interesting
"
- Many more NT kernel objects and functions are implemented, to
  support anti-cheat systems that load kernel drivers.
"
Maybe work on the snap again ?

**Comment by themsiqueira** [comment]
Really? can you make a pull request?

**Comment by WarpWing** [comment]
> Really? can you make a pull request?

I think I can do a PR though I'm not sure it will work. I'll make a stable build on Debian and get back to you. Sorry if I'm necroposting but I also want valorant to work on linux so we'll see

**Comment by themsiqueira** [comment]
@WarpWing okay, but if works fell free to send a pr, now this repo is deprecated

**Comment by WarpWing** [comment]
> 
> 
> @WarpWing okay, but if works fell free to send a pr, now this repo is deprecated

Sorry, school has been a bish. I'll try to make time xd
